[package]
name = "sniff"
version = "0.0.1"
edition = "2021"
authors = [ "MadKarma <me@madkarma.top>" ]
repository = "https://github.com/madkarmaa/sniff"

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version="0.7.2", features=['http', 'axum'] }
worker-macros = { version="0.7.2", features=['http'] }
axum  = { version = "0.7", default-features = false, features=['json', 'macros'] }
tower-service = "0.3.2"
tokio = { version = "1", default-features = false, features = ["sync"] }
console_error_panic_hook = { version = "0.1.1" }

gpapi = { path = "./gpapi" }
googleplay-protobuf = "3"

serde = { version = "1.0.219", features = ["derive"] }

utoipa = { version = "5.4", features = ["axum_extras"] }

[workspace]
members = ["gpapi", "oauth2aas"]

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"

[lints]
workspace = true
