name = "sniff-v2"
main = "build/worker/shim.mjs"
compatibility_date = "2025-04-25"

routes = [
  { pattern = "sniff.madkarma.top/v2", zone_name = "madkarma.top" },
  { pattern = "sniff.madkarma.top/v2/*", zone_name = "madkarma.top" },
  { pattern = "sniff.madkarma.top/*", zone_name = "madkarma.top" }
]

[build]
command = "cargo install -q --locked worker-build@0.8.6 && worker-build --release"

[vars]
DEVICE_NAME="px_9a"
